### ISSUE TITLE
Wen A13 kernel sar

### ISSUE THREAD

**Issue by NotZeetaa** [projects-nexus/nexus_kernel_xiaomi_lavender#1]

**Comment by shubhamxdd** [comment]
Wen @NotZeetaa

**Comment by NotZeetaa** [comment]
> Wen @NotZeetaa

Soon @shubhamxdd

**Comment by ImSpiDy** [comment]
@NotZeetaa Wen

**Comment by ImSpiDy** [comment]
@ImSpiDy Wen wen wen

**Comment by ImSpiDy** [comment]
@NotZeetaa But wen

**Comment by NotZeetaa** [comment]
> @NotZeetaa But wen

In 69 minutes

**Comment by reaPeR1010** [comment]
@NotZeetaa Wtf

**Comment by reaPeR1010** [comment]
@reaPeR1010 Chutiya

**Comment by reaPeR1010** [comment]
@reaPeR1010 Bsdika

**Comment by ImSpiDy** [comment]
@reaPeR1010 Chup randi

**Comment by reaPeR1010** [comment]
@reaPeR1010 .thanos

**Comment by ImSpiDy** [comment]
@reaPeR1010 K bhai lol

**Comment by ImSpiDy** [comment]
@reaPeR1010 :- Phuloo Ka Raja Gulaab Kaato me Rehta hai Jeewan ka Nirmata jaato me rehta hai😂

**Comment by reaPeR1010** [comment]
@ImSpiDy Madarchod Randi ke bacche Oye bosdike madarchod bhen ke lode tere gand me lohe ka danda garam karke dalu randwe tujhetho gali ke kutte gand pe chut rakh ke katenge me bata raha hu tere lode pe madhu makkhi Katelode ke ando pe Road roller chale tu kab bathroom me muthne Jaye tho Tera loda ghir Jaye fir tere ando me se lizard ke bacche nikle teko kidnap Kare aur childporn banaye maa ke chuttad ke lode tere saat Johnny sins rape Kare aur jab wo teko anal de tab loda andar fas Jaye bkl tere jhaat pe waxing karunga me dhek lio fir jab tu chillayega na tab tere muh me Mai gai ka gobar dalunga sale tere gand ke balo pe tel laga ke jala du me teko Anaconda leke gand me dalu tho muh se nikle maa ke lode hamesha chutiyo jaisa bartav kartha he tu maa ke Dai chawal drugs tere gand Me dalunga thi tatti nahi nikle maa darchod kabhi teko Marne ka mouka mil gaya na tho bas I'll do my best to get that tatti outof you aur tere jaise chutio ko is duniya me jagaha bhi nahi maa ke lode bandarchod tere gand me chitiya Kate wo bhi bullet ants maadarchod samj nahi aaraha tere baap NE teko kya khake paida kiya Tha kesa chutiya he tu rand ke bacche teko shadi me khana khane na mile teko gand pe 4 thappad mare sab log aur blade se likhe I want anal madarchod bosdike maccharki tatte ke baal chutiye maa ke chut pe ghode ka Lund tere gand me jaltha hu koila Dale bhen ke lode MAA KI CHUT MAI TALWAR DUNGA BC CHUT FAT JAEGI AUR USME SE ITNA KHOON NIKLEGA MZA AJAEGA DEKHNE KA SALE MAA KE BHOSDE SE BAHR AJA FIR BAAP SE ZUBAN DA TERI MAA KI CHUT CHOD CHOD KE BHOSDABNADU MADARCHOD AUR USKE UPAR CENENT LAGADU KI TERE JESA GANDU INSAAN KABHI BAHR NA A SKE ESI GANDI CHUT MAI SE LODA LASUN MADRCHOD TERI MAA KI CHUT GASTI AMA KA CHUTIA BACHA TERI MAA KO CHOD CHOD K PAGAL KAR DUNGA MAA K LODY KISI SASTIII RANDII K BACHY TERI MAA KI CHOOT MAIN TEER MAARUN GANDU HARAMI TERI COLLEGE JATI BAJI KA ROAD PEY RAPE KARONGANDU KI OLAAD HARAM KI NASAL PAPA HUN TERA BHEN PESH KAR AB PAPA KO TERI MAA KKALE KUSS MAIN KISI !

**Comment by ImSpiDy** [comment]
@reaPeR1010 Madarchod Randi ke bacche Oye bosdike madarchod bhen ke lode tere gand me lohe ka danda garam karke dalu randwe tujhetho gali ke kutte gand pe chut rakh ke katenge me bata raha hu tere lode pe madhu makkhi Katelode ke ando pe Road roller chale tu kab bathroom me muthne Jaye tho Tera loda ghir Jaye fir tere ando me se lizard ke bacche nikle teko kidnap Kare aur childporn banaye maa ke chuttad ke lode tere saat Johnny sins rape Kare aur jab wo teko anal de tab loda andar fas Jaye bkl tere jhaat pe waxing karunga me dhek lio fir jab tu chillayega na tab tere muh me Mai gai ka gobar dalunga sale tere gand ke balo pe tel laga ke jala du me teko Anaconda leke gand me dalu tho muh se nikle maa ke lode hamesha chutiyo jaisa bartav kartha he tu maa ke Dai chawal drugs tere gand Me dalunga thi tatti nahi nikle maa darchod kabhi teko Marne ka mouka mil gaya na tho bas I'll do my best to get that tatti outof you aur tere jaise chutio ko is duniya me jagaha bhi nahi maa ke lode bandarchod tere gand me chitiya Kate wo bhi bullet ants maadarchod samj nahi aaraha tere baap NE teko kya khake paida kiya Tha kesa chutiya he tu rand ke bacche teko shadi me khana khane na mile teko gand pe 4 thappad mare sab log aur blade se likhe I want anal madarchod bosdike maccharki tatte ke baal chutiye maa ke chut pe ghode ka Lund tere gand me jaltha hu koila Dale bhen ke lode MAA KI CHUT MAI TALWAR DUNGA BC CHUT FAT JAEGI AUR USME SE ITNA KHOON NIKLEGA MZA AJAEGA DEKHNE KA SALE MAA KE BHOSDE SE BAHR AJA FIR BAAP SE ZUBAN DA TERI MAA KI CHUT CHOD CHOD KE BHOSDABNADU MADARCHOD AUR USKE UPAR CENENT LAGADU KI TERE JESA GANDU INSAAN KABHI BAHR NA A SKE ESI GANDI CHUT MAI SE LODA LASUN MADRCHOD TERI MAA KI CHUT GASTI AMA KA CHUTIA BACHA TERI MAA KO CHOD CHOD K PAGAL KAR DUNGA MAA K LODY KISI SASTIII RANDII K BACHY TERI MAA KI CHOOT MAIN TEER MAARUN GANDU HARAMI TERI COLLEGE JATI BAJI KA ROAD PEY RAPE KARONGANDU KI OLAAD HARAM KI NASAL PAPA HUN TERA BHEN PESH KAR AB PAPA KO TERI MAA KKALE KUSS MAIN KISI !

**Comment by reaPeR1010** [comment]
@ImSpiDy Behen ke lode madahrchod teri ma randi bhsdk tera pyra khandan randi teri kandan kai ma ka bhods lund katta madarchod tere lund pe road roller chale tere behen ki chut kate tura khandan ke gand me bomb phute teri ma ke bur me 100 log ke lund teri behen ke bur me 100 log ke lund madarchod behenchod mai ka loda behen ka loda randi teri behen ma ki chut behen ki chut teri chut ki chut harami phate hue condom ke nateeje tera baap ko paisa nahi tha to uses condom se teri maa ko chooda benchod lodo hai tu sabka chusta gay lund hai nahi be lund akuad me re hamare desh ki taraf bhi dekha to tatte ukhad ke kutto ko keladenge madharchod Madarchod Randi ke bacche.Oye bosdike madarchod bhen ke lode tere gand me lohe ka danda garam karke dalu randwe tujhetho gali ke kutte gand pe chut rakh ke katenge me bata raha hu tere lode pe madhu makkhi Katelode ke ando pe Road roller chale tu kab bathroom me muthne Jaye tho Tera loda ghir Jaye fir tere ando me se lizard ke bacche nikle teko kidnap Kare aur childporn banaye maa ke chuttad ke lode tere saat Johnny sins rape Kare aur jab wo teko anal de tab loda andar fas Jaye bkl tere jhaat pe waxing karunga me dhek lio fir jab tu chillayega na tab tere muh me Mai gai ka gobar dalunga sale tere gand ke balo pe tel laga ke jala du me teko Anaconda leke gand me dalu tho muh se nikle maa ke lode hamesha chutiyo jaisa bartav kartha he tu maa ke Dai chawal drugs tere gand Me dalunga thi tatti nahi nikle maa darchod kabhi teko Marne ka mouka mil gaya na tho bas I'll do my best to get that tatti outof you aur tere jaise chutio ko is duniya me jagaha bhi nahi maa ke lode bandarchod tere gand me chitiya Kate wo bhi bullet ants maadarchod samj nahi aaraha tere baap NE teko kya khake paida kiya Tha kesa chutiya he tu rand ke bacche teko shadi me khana khane na mile teko gand pe 4 thappad mare sab log aur blade se likhe I want anal madarchod bosdike maccharki tatte ke baal chutiye maa ke chut pe ghode ka Lund tere gand me jaltha hu koila Dale bhen ke lode MAA KI CHUT MAI TALWAR DUNGA BC CHUT FAT JAEGI AUR USME SE ITNA KHOON NIKLEGA MZA AJAEGA DEKHNE KA SALE MAA KE BHOSDE SE BAHR AJA FIR BAAP SE ZUBAN DA TERI MAA KI CHUT CHOD CHOD KE BHOSDABNADU MADARCHOD AUR USKE UPAR CENENT LAGADU KI TERE JESA GANDU INSAAN KABHI BAHR NA A SKE ESI GANDI CHUT MAI SE LODA LASUN MADRCHOD TERI MAA KI CHUT GASTI AMA KA CHUTIA BACHA TERI MAA KO CHOD CHOD K PAGAL KAR DUNGA MAA K LODY KISI SASTIII RANDII K BACHY TERI MAA KI CHOOT MAIN TEER MAARUN GANDU HARAMI TERI COLLEGE JATI BAJI KA ROAD PEY RAPE KARONGANDU KI OLAAD HARAM KI NASAL PAPA HUN TERA BHEN PESH KAR AB PAPA KO TERI MAA KKALE KUSS MAIN KISI loda leke muh me nachne wale ma ki jaat lund kate tera tiri bb ko chode duniya tiri gand me parmanu dhamaka teri ma ka buur me garam oil ki kadhai teri behen ki bane porn aur upload ho pornhub me teri ma ko 100 logo ne choda tab tu paida hua tra papa gay tu gay tera khandan gay bc mc maki chut belen ki lodi ma ki lodi behen teri randi ma teri randi loda undono ke muh me loda katgaya to muh me lele aur kuch hame bola to tera loda tere muh me deke tere gand se nikalenge madarchod beti teru chodaye beti teri rundi teri beti ki bur me 1000 logo ka lund teri beti ka gangbang tere papa be lund nund na hone ke karan teri ma rundi teri ma randi hone ke karan tu aur tera bhai behen teri behen radi kuki teri ma randi behen radi hone ke karan ro 1000 se choda ke uske 10000 bacche tere lund par hathi dore teri gand me chiti kate kera pura satyanash ho *Main roz teri* *behno ki banjar chut me* *apna lawda daalke andar* *haryali lata tha magar aaj* *unke ke baare me* *sunke mujhe bhut afsos* *huwa..ki unko ab bada loudha chahye..ab mera balatkaaari* *lawda lagataar 4 ghante tk* *apne muh me kon* *rakhega..vo teri* *behne hi thi jo apni kaali* *magar rasilli chut mere* *saamne khol deti aur* *zameen pe naagin ki tarah* *rengne lgti thi jaise ki* *kisine unki chut pe naariyal* *tod diya ho vo b bada wala* *mumbai ka naariyal.

**Comment by shubhamxdd** [comment]
@reaPeR1010 Wow RTR here

**Comment by MxkulSharma** [comment]
XD

**Comment by ImSpiDy** [comment]
@shubhamxdd Riya The Randi 👌👌👌

**Comment by shubhamxdd** [comment]
@ImSpiDy Riya The Randi 👌👌👌

**Comment by shubhamxdd** [comment]
@reaPeR1010

**Comment by ahkehra** [comment]
@reaPeR1010 hi babe I mean Riya The Randi.

**Comment by tattwamashi** [comment]
Lmao no, me Join the party

**Comment by tattwamashi** [comment]
> 

Behen ke lode madahrchod teri ma randi bhsdk tera pyra khandan randi teri kandan kai ma ka bhods lund katta madarchod tere lund pe road roller chale tere behen ki chut kate tura khandan ke gand me bomb phute teri ma ke bur me 100 log ke lund teri behen ke bur me 100 log ke lund madarchod behenchod mai ka loda behen ka loda randi teri behen ma ki chut behen ki chut teri chut ki chut harami phate hue condom ke nateeje tera baap ko paisa nahi tha to uses condom se teri maa ko chooda benchod lodo hai tu sabka chusta gay lund hai nahi be lund akuad me re hamare desh ki taraf bhi dekha to tatte ukhad ke kutto ko keladenge madharchod Madarchod Randi ke bacche.Oye bosdike madarchod bhen ke lode tere gand me lohe ka danda garam karke dalu randwe tujhetho gali ke kutte gand pe chut rakh ke katenge me bata raha hu tere lode pe madhu makkhi Katelode ke ando pe Road roller chale tu kab bathroom me muthne Jaye tho Tera loda ghir Jaye fir tere ando me se lizard ke bacche nikle teko kidnap Kare aur childporn banaye maa ke chuttad ke lode tere saat Johnny sins rape Kare aur jab wo teko anal de tab loda andar fas Jaye bkl tere jhaat pe waxing karunga me dhek lio fir jab tu chillayega na tab tere muh me Mai gai ka gobar dalunga sale tere gand ke balo pe tel laga ke jala du me teko Anaconda leke gand me dalu tho muh se nikle maa ke lode hamesha chutiyo jaisa bartav kartha he tu maa ke Dai chawal drugs tere gand Me dalunga thi tatti nahi nikle maa darchod kabhi teko Marne ka mouka mil gaya na tho bas I'll do my best to get that tatti outof you aur tere jaise chutio ko is duniya me jagaha bhi nahi maa ke lode bandarchod tere gand me chitiya Kate wo bhi bullet ants maadarchod samj nahi aaraha tere baap NE teko kya khake paida kiya Tha kesa chutiya he tu rand ke bacche teko shadi me khana khane na mile teko gand pe 4 thappad mare sab log aur blade se likhe I want anal madarchod bosdike maccharki tatte ke baal chutiye maa ke chut pe ghode ka Lund tere gand me jaltha hu koila Dale bhen ke lode MAA KI CHUT MAI TALWAR DUNGA BC CHUT FAT JAEGI AUR USME SE ITNA KHOON NIKLEGA MZA AJAEGA DEKHNE KA SALE MAA KE BHOSDE SE BAHR AJA FIR BAAP SE ZUBAN DA TERI MAA KI CHUT CHOD CHOD KE BHOSDABNADU MADARCHOD AUR USKE UPAR CENENT LAGADU KI TERE JESA GANDU INSAAN KABHI BAHR NA A SKE ESI GANDI CHUT MAI SE LODA LASUN MADRCHOD TERI MAA KI CHUT GASTI AMA KA CHUTIA BACHA TERI MAA KO CHOD CHOD K PAGAL KAR DUNGA MAA K LODY KISI SASTIII RANDII K BACHY TERI MAA KI CHOOT MAIN TEER MAARUN GANDU HARAMI TERI COLLEGE JATI BAJI KA ROAD PEY RAPE KARONGANDU KI OLAAD HARAM KI NASAL PAPA HUN TERA BHEN PESH KAR AB PAPA KO TERI MAA KKALE KUSS MAIN KISI loda leke muh me nachne wale ma ki jaat lund kate tera tiri bb ko chode duniya tiri gand me parmanu dhamaka teri ma ka buur me garam oil ki kadhai teri behen ki bane porn aur upload ho pornhub me teri ma ko 100 logo ne choda tab tu paida hua tra papa gay tu gay tera khandan gay bc mc maki chut belen ki lodi ma ki lodi behen teri randi ma teri randi loda undono ke muh me loda katgaya to muh me lele aur kuch hame bola to tera loda tere muh me deke tere gand se nikalenge madarchod beti teru chodaye beti teri rundi teri beti ki bur me 1000 logo ka lund teri beti ka gangbang tere papa be lund nund na hone ke karan teri ma rundi teri ma randi hone ke karan tu aur tera bhai behen teri behen radi kuki teri ma randi behen radi hone ke karan ro 1000 se choda ke uske 10000 bacche tere lund par hathi dore teri gand me chiti kate kera pura satyanash ho Main roz teri behno ki banjar chut me apna lawda daalke andar haryali lata tha magar aaj unke ke baare me sunke mujhe bhut afsos huwa..ki unko ab bada loudha chahye..ab mera balatkaaari lawda lagataar 4 ghante tk apne muh me kon rakhega..vo teri behne hi thi jo apni kaali magar rasilli chut mere saamne khol deti aur zameen pe naagin ki tarah rengne lgti thi jaise ki kisine unki chut pe naariyal tod diya ho vo b bada wala *mumbai ka naariyal

**Comment by tattwamashi** [comment]
Ah yes lmao

**Comment by ahkehra** [comment]
@ElectroPerf ok bhai @reaPeR1010 RTR Wen come

**Comment by ElectroPerf** [comment]
> @ElectroPerf ok bhai @reaPeR1010 RTR Wen come

Thenks... Anywayys,, credits @anupamroy777
![IMG-20220222-WA0002](https://user-images.githubusercontent.com/76483474/155016462-27c8a278-ba74-4788-98eb-2cec1f4dfcf0.jpg)

**Comment by tattwamashi** [comment]
> @ElectroPerf ok bhai @reaPeR1010 RTR Wen come

Thenks 
![IMG_20220222_010341_978](https://user-images.githubusercontent.com/76483474/155016633-a19a1e12-cc08-424c-80df-04a672ef7dbd.jpg)
bhoi... Credits @anupamroy777

**Comment by akirasupr** [comment]
Lmfao

**Comment by tattwamashi** [comment]
AHAHAHAHA

**Comment by ahkehra** [comment]
@ElectroPerf Lmfao

**Comment by tattwamashi** [comment]
Lmao

**Comment by Divyanshu-Modi** [comment]
Hum  bhi iss spam Mai yogdaan denge

**Comment by ahkehra** [comment]
@Divyanshu-Modi Geetaa supremacy

**Comment by tattwamashi** [comment]
Ah yyes, the @atom-x-devs lead @Divyanshu-Modi annd co lead me contributing to nexus project issues🔥😂😂

Wen appreciate @akirasupr @NotZeetaa

**Comment by ahkehra** [comment]
@ElectroPerf धन्यवाद आपका lmao

**Comment by tattwamashi** [comment]
Lmfao

**Comment by ImSpiDy** [comment]
@ElectroPerf Madad ke liye shukriya

**Comment by ImSpiDy** [comment]
@NotZeetaa bosadike wen online

**Comment by NotZeetaa** [comment]
> Ah yyes, the @Atom-X-Devs lead @Divyanshu-Modi annd co lead me contributing to nexus project issues🔥😂😂
> 
> Wen appreciate @akirasupr @NotZeetaa

Lmao

**Comment by NotZeetaa** [comment]
> @NotZeetaa bosadike wen online

Im Online Bish and half ded

**Comment by NotZeetaa** [comment]
Gmail Spammers

**Comment by ahkehra** [comment]
@NotZeetaa Hello geetaa bahan

**Comment by tattwamashi** [comment]
Me propose geeta ssuuuun😂

**Comment by ahkehra** [comment]
@ElectroPerf She likes 144hz display oc only.

**Comment by tattwamashi** [comment]
> @ElectroPerf She likes 144hz display oc only.

Ah then parvinder might be interested lmao

**Comment by ahkehra** [comment]
@ElectroPerf Lmfao 🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by tattwamashi** [comment]
> @ElectroPerf Lmfao 🤣🤣🤣🤣🤣🤣🤣🤣

😂😂😂🔥🔥

**Comment by redducc** [comment]
@ElectroPerf gay h Kya lode

**Comment by tattwamashi** [comment]
> @ElectroPerf gay h Kya lode

Atleast not a shemale like sushmita 😂🖕

**Comment by redducc** [comment]
> > @ElectroPerf gay h Kya lode
> 
> Atleast not a shemale like sushmita 😂🖕

But you still gay

**Comment by ImPrashantt** [comment]
@sushmit1

**Comment by UsiFX** [comment]
@ImPrashantt Lol

**Comment by Prashant-1695** [comment]
@ImPrashantt Lol

**Comment by reaPeR1010** [comment]
@ImPrashantt Wah Bhai randibazzi started LoL

**Comment by ahkehra** [comment]
@reaPeR1010 Ok Riya The Randi

**Comment by shubhamxdd** [comment]
@akirasupr Hemlo

**Comment by Prashant-1695** [comment]
@reaPeR1010 u busy in riya service

**Comment by shubhamxdd** [comment]
@ImPrashantt reech moment soon

**Comment by ahkehra** [comment]
@shubhamxdd Stonks

**Comment by shubhamxdd** [comment]
@akirasupr

**Comment by NotZeetaa** [comment]
Why i opened this issue
F

**Comment by shubhamxdd** [comment]
@NotZeetaa why

**Comment by tattwamashi** [comment]
Cuz  whyy not lmao @NotZeetaa

**Comment by ImSpiDy** [comment]
@NotZeetaa Bcoz you are chutiya and gay

**Comment by shubhamxdd** [comment]
@ImSpiDy Destruction x 100

**Comment by NotZeetaa** [comment]
@ImSpiDy A12 wen sae

**Comment by NotZeetaa** [comment]
> @ImSpiDy A13 wen sar

**Comment by NotZeetaa** [comment]
Wtf Ok Nice

**Comment by ImSpiDy** [comment]
@NotZeetaa Soom With GeetaaOS

**Comment by NotZeetaa** [comment]
@ImSpiDy Based on Miui

**Comment by arnavpuranik** [comment]
@NotZeetaa GeetaUI

**Comment by ImSpiDy** [comment]
@NotZeetaa Nooooo gwad plox Noooooo

**Comment by shubhamxdd** [comment]
@NotZeetaa stock kernel nexus v5 oc vershan 😤😤

**Comment by ImSpiDy** [comment]
@shubhamxdd HMP-Qti-NewCam soom

**Comment by shubhamxdd** [comment]
@ImSpiDy Semx

**Comment by NotZeetaa** [comment]
@shubhamxdd LET ME PLAY MY VALORANT

**Comment by Prashant-1695** [comment]
@NotZeetaa Accha bhai ok

**Comment by shubhamxdd** [comment]
@NotZeetaa No valolund only pabji

**Comment by tattwamashi** [comment]
Geeta wen accept parvinder cuz https://github.com/projects-nexus/android_kernel_xiaomi_lavender-LTO/issues/1#issuecomment-1047193304
