### ISSUE TITLE
as: unrecognized option '-EL'

### ISSUE THREAD

**Issue by gas0324** [projects-nexus/nexus_kernel_xiaomi_lavender#6]
I'm trying to compile this kernel
```
https://github.com/crdroidandroid/android_kernel_xiaomi_lavender 
```

This tool is used
```
https://github.com/kdrag0n/proton-clang
```

Commands Executed
```
make O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-androideabi- lavender-perf_defconfig

make O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-androideabi- -j4
```
目前遇到这样的错误
```
  LDS     arch/arm64/kernel/vdso32/vdso.lds
  HOSTCC  arch/arm64/kernel/vdso32/../../../arm/vdso/vdsomunge
/home/asd/toolchains/proton-clang/bin/as: unrecognized option '-EL'
clang-13: error: assembler command failed with exit code 1 (use -v to see invocation)
../arch/arm64/kernel/vdso32/Makefile:157: recipe for target 'arch/arm64/kernel/vdso32/sigreturn.o' failed
make[2]: *** [arch/arm64/kernel/vdso32/sigreturn.o] Error 1
make[2]: *** 正在等待未完成的任务....
/home/asd/toolchains/proton-clang/bin/as: unrecognized option '-EL'
clang-13: error: assembler command failed with exit code 1 (use -v to see invocation)
../arch/arm64/kernel/vdso32/Makefile:155: recipe for target 'arch/arm64/kernel/vdso32/vgettimeofday.o' failed
make[2]: *** [arch/arm64/kernel/vdso32/vgettimeofday.o] Error 1
arch/arm64/Makefile:191: recipe for target 'vdso_prepare' failed
make[1]: *** [vdso_prepare] Error 2
make[1]: 离开目录“/home/asd/android_kernel_xiaomi_lavender/out”
Makefile:152: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2
```

**Comment by gas0324** [comment]
$ ${CROSS_COMPILE}ld -v
GNU ld (GNU Binutils) 2.36.1

**Comment by wHo-EM-i** [comment]
@gas0324 Which branch? If its los-2 then that branch is wip

**Comment by Prashant-1695** [comment]
Revert : https://github.com/crdroidandroid/android_kernel_xiaomi_lavender/commit/4bdc7085a837d121d10164a0067726e6175c1061
https://github.com/crdroidandroid/android_kernel_xiaomi_lavender/commit/99afbd7ef2f5be331f7c3fa4216f99e2937d91e6 
And define linker in your build script

**Comment by gas0324** [comment]
> https://github.com/crdroidandroid/android_kernel_xiaomi_lavender

My rom is crDroid 9.0, Android version 13, and I use 13.0 branch

**Comment by Prashant-1695** [comment]
If you don't know a13 won't boot on proton clang

**Comment by gas0324** [comment]
> If you don't know a13 won't boot on proton clang

What should I do

**Comment by Prashant-1695** [comment]
> > If you don't know a13 won't boot on proton clang
> 
> What should I do

Use ROMs default compiler

**Comment by gas0324** [comment]
> Revert : [crdroidandroid@4bdc708](https://github.com/crdroidandroid/android_kernel_xiaomi_lavender/commit/4bdc7085a837d121d10164a0067726e6175c1061) [crdroidandroid@99afbd7](https://github.com/crdroidandroid/android_kernel_xiaomi_lavender/commit/99afbd7ef2f5be331f7c3fa4216f99e2937d91e6) And define linker in your build script
```
$  git reset --hard 4bdc708
正在检出文件: 100% (57093/57093), 完成.
HEAD 现在位于 4bdc7085a837 build: Enable Optimizations through build.sh
$  make O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-androideabi- lavender-perf_defconfig
make[1]: 进入目录“/home/asd/android_kernel_xiaomi_lavender/out”
  HOSTCC  scripts/basic/fixdep
  GEN     ./Makefile
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
arch/arm64/configs/lavender-perf_defconfig:1146:warning: override: reassigning to symbol BPF_JIT
arch/arm64/configs/lavender-perf_defconfig:5125:warning: override: reassigning to symbol BINARY_PRINTF
warning: (CRYPTO_HEH) selects CRYPTO_POLY_HASH_ARM64_CE which has unmet direct dependencies (CRYPTO && ARM64_CRYPTO && ARM64 && KERNEL_MODE_NEON)
warning: (CRYPTO_HEH) selects CRYPTO_POLY_HASH_ARM64_CE which has unmet direct dependencies (CRYPTO && ARM64_CRYPTO && ARM64 && KERNEL_MODE_NEON)
#
# configuration written to .config
#
make[1]: 离开目录“/home/asd/android_kernel_xiaomi_lavender/out”
```

**Comment by gas0324** [comment]
> > > If you don't know a13 won't boot on proton clang
> > 
> > 
> > What should I do
> 
> Use ROMs default compiler

Could you be more detailed? I don't know how to do it

**Comment by gas0324** [comment]
> > > If you don't know a13 won't boot on proton clang
> > 
> > 
> > What should I do
> 
> Use ROMs default compiler

Where can I download the compiler

**Comment by Prashant-1695** [comment]
> > > > If you don't know a13 won't boot on proton clang
> > > 
> > > 
> > > What should I do
> > 
> > 
> > Use ROMs default compiler
> 
> Where can I download the compile

**Comment by NotZeetaa** [comment]
@gas0324 Buildboob be like

**Comment by xenxynon** [comment]
@Prashant-1695 Use neksux 15

**Comment by ImSpiDy** [comment]
@NotZeetaa No bulli plox 😢😢😢

**Comment by kawaaii** [comment]
@Prashant-1695 You can just lookup on the orgs 
Let me help you with that
https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b
This should work out!

**Comment by gas0324** [comment]
> Let me help you with that

Thanks, I'll try
